import { normalizeRecoveryResponse } from "./app/content/recoveryResponse";

// Generated by the OpenNext build before Wrangler bundles this entrypoint.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore The generated module does not exist in a fresh checkout.
import openNextWorker from "./.open-next/worker.js";

// Keep OpenNext's Durable Object exports available to Wrangler.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore The generated module does not exist in a fresh checkout.
export { DOQueueHandler } from "./.open-next/worker.js";

const worker = {
  async fetch(request: Request, env: CloudflareEnv, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);
    if (isCmsPrivatePath(url.pathname) && env.CMS_EDITOR_ENABLED !== "true") {
      return finalizeResponse(
        url,
        new Response("Not found", { status: 404 }),
        env,
      );
    }
    const accept = request.headers.get("accept") ?? "";
    if (
      request.method === "GET" &&
      accept.includes("text/markdown") &&
      request.headers.get("x-md-probe") !== "1"
    ) {
      for (const pathname of markdownCandidates(url.pathname)) {
        const probeUrl = new URL(pathname, url);
        const probeHeaders = new Headers(request.headers);
        probeHeaders.set("x-md-probe", "1");
        const probe = await openNextWorker.fetch(
          new Request(probeUrl, { method: "GET", headers: probeHeaders }),
          env,
          ctx,
        );
        if (probe.ok && (await probe.clone().text()).length > 0) {
          const headers = new Headers(probe.headers);
          headers.set("x-served-as", "markdown");
          return finalizeResponse(
            url,
            new Response(probe.body, {
              status: probe.status,
              statusText: probe.statusText,
              headers,
            }),
            env,
          );
        }
      }
    }

    const response = await normalizeRecoveryResponse(
      await openNextWorker.fetch(request, env, ctx),
    );
    return finalizeResponse(url, response, env);
  },
};

function markdownCandidates(pathname: string): string[] {
  if (pathname === "/" || pathname === "") return ["/index.md"];
  const trimmed = pathname.replace(/\/$/, "");
  return [`${trimmed}/index.md`, `${trimmed}.md`];
}

function isCmsPrivatePath(pathname: string): boolean {
  return (
    pathname === "/edit" ||
    pathname.startsWith("/edit/") ||
    pathname === "/api/cms" ||
    pathname.startsWith("/api/cms/")
  );
}

function finalizeResponse(
  url: URL,
  response: Response,
  env: CloudflareEnv,
): Response {
  const headers = new Headers(response.headers);
  if (isCmsPrivatePath(url.pathname)) {
    headers.set("cache-control", "private, no-store");
    headers.set("x-robots-tag", "noindex, nofollow");
  }
  if (
    url.hostname.endsWith(".workers.dev") ||
    url.hostname.endsWith(".pages.dev") ||
    url.hostname === env.CMS_PREVIEW_HOSTNAME
  ) {
    headers.set("x-robots-tag", "noindex, nofollow");
  }
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

export default worker;
