import { normalizeRecoveryResponse } from "./app/content/recoveryResponse";

// Generated by the OpenNext build before Wrangler bundles this entrypoint.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore The generated module does not exist in a fresh checkout.
import openNextWorker from "./.open-next/worker.js";

// Keep OpenNext's Durable Object exports available to Wrangler.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore The generated module does not exist in a fresh checkout.
export { DOQueueHandler } from "./.open-next/worker.js";

const worker = {
  async fetch(request: Request, env: CloudflareEnv, ctx: ExecutionContext): Promise<Response> {
    const response = await openNextWorker.fetch(request, env, ctx);
    return normalizeRecoveryResponse(response);
  },
};

export default worker;
